# Generated by Django 3.0.5 on 2020-04-26 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='image_src',
            field=models.TextField(default=''),
        ),
    ]
